--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期五, 09 二月, 2018 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS `sys_access` CASCADE
;
DROP TABLE IF EXISTS `sys_account` CASCADE
;
DROP TABLE IF EXISTS `sys_account_role` CASCADE
;
DROP TABLE IF EXISTS `sys_role` CASCADE
;
DROP TABLE IF EXISTS `sys_role_access` CASCADE
;

--  Create Tables 
CREATE TABLE `sys_access`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '权限id.自增长',
	`name` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '权限名称',
	`desc` NVARCHAR(128) NOT NULL DEFAULT '' COMMENT '权限描述',
	`enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否开启。默认权限是开启的。 如果权限关闭，则所有具有该权限的角色都无法使用该权限',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`),
	UNIQUE `UQ_sys_access_name`(`name`)

)  COMMENT='系统表：权限信息'
;


CREATE TABLE `sys_account`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`account_name` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '账户名称',
	`password_secret` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SHA1(密码+salt)',
	`salt` NVARCHAR(16) NOT NULL DEFAULT '' COMMENT '加密盐值',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`),
	UNIQUE `UQ_sys_account_account_name`(`account_name`)

)  COMMENT='系统表：账户信息表'
;


CREATE TABLE `sys_account_role`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长id',
	`account_id` BIGINT NOT NULL DEFAULT -1 COMMENT '账户id',
	`role_id` BIGINT NOT NULL DEFAULT -1 COMMENT '角色id',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`),
	UNIQUE `UQ_sys_account_role`(`account_id`, `role_id`)

)  COMMENT='系统表：账户角色关系'
;


CREATE TABLE `sys_role`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长id',
	`name` NVARCHAR(32) NOT NULL DEFAULT '' COMMENT '角色名称',
	`desc` NVARCHAR(64) DEFAULT '' COMMENT '角色描述',
	`enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`)

)  COMMENT='系统角色表'
;


CREATE TABLE `sys_role_access`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增id',
	`role_id` BIGINT NOT NULL DEFAULT -1 COMMENT '角色id',
	`access_id` BIGINT NOT NULL DEFAULT -1 COMMENT '权限id',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`),
	UNIQUE `UQ_sys_role_access`(`role_id`, `access_id`)

)  COMMENT='系统角色具备权限信息表'
;



SET FOREIGN_KEY_CHECKS=1;
