--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 19 十二月, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 

DROP TABLE IF EXISTS `sys_role` CASCADE
;
CREATE TABLE `sys_role`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增长id',
	`name` NVARCHAR(32) NOT NULL DEFAULT '' COMMENT '角色名称',
	`desc` NVARCHAR(64) DEFAULT '' COMMENT '角色描述',
	`enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`)

)  COMMENT='系统角色表'
;


