--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 19 十二月, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 

DROP TABLE IF EXISTS `sys_account` CASCADE
;
CREATE TABLE `sys_account`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`account_name` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '账户名称',
	`password_secret` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT 'SHA1(密码+salt)',
	`salt` NVARCHAR(16) NOT NULL DEFAULT '' COMMENT '加密盐值',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`),
	UNIQUE `UQ_sys_account_account_name`(`account_name`)

)  COMMENT='系统表：账户信息表'
;


