--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 19 十二月, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 

DROP TABLE IF EXISTS `sys_access` CASCADE
;
CREATE TABLE `sys_access`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '权限id.自增长',
	`name` NVARCHAR(64) NOT NULL DEFAULT '' COMMENT '权限名称',
	`desc` NVARCHAR(128) NOT NULL DEFAULT '' COMMENT '权限描述',
	`enable` BIT(1) NOT NULL DEFAULT 1 COMMENT '是否开启。默认权限是开启的。 如果权限关闭，则所有具有该权限的角色都无法使用该权限',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`),
	UNIQUE `UQ_sys_access_name`(`name`)

)  COMMENT='系统表：权限信息'
;


