--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.0.1106
--   Created On : 星期二, 19 十二月, 2017 
--   DBMS       : MySql 
--   -------------------------------------------------- 

DROP TABLE IF EXISTS `sys_role_access` CASCADE
;
CREATE TABLE `sys_role_access`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增id',
	`role_id` BIGINT NOT NULL DEFAULT -1 COMMENT '角色id',
	`access_id` BIGINT NOT NULL DEFAULT -1 COMMENT '权限id',
	`create_time` DATETIME(0) NOT NULL DEFAULT now(),
	`update_time` DATETIME(0) NOT NULL DEFAULT now(),
	PRIMARY KEY (`id`)

)  COMMENT='系统角色具备权限信息表'
;


